language: rust
rust:
  - nightly

script:
  - npm install
  - yarn build
  - cargo build
  - npm install travis-github-lint-status eslint eslint-plugin-react
  - ./node_modules/travis-github-lint-status/index.js
