[package]
name = "rustw"
version = "0.1.0"
authors = ["Nick Cameron <ncameron@mozilla.com>"]
repository = "https://github.com/nrc/rustw"
readme = "README.md"
license = "Apache-2.0/MIT"
build = "build.rs"
categories = ["development-tools"]

[[bin]]
name = "cargo-src"

[dependencies]
url = "0.5"
serde = "1.0"
serde_json = "1.0"
serde_derive = "1.0"
toml = "0.4"
rls-analysis = "0.10"
rls-blacklist = "0.1.0"
rls-span = "0.4"
rls-vfs = "0.4.4"
log = "0.3"
env_logger = "0.3"
rustdoc-highlight = { git = "https://github.com/nrc/rustdoc-highlight" }
futures = "0.1.14"
hyper="0.11"

[build-dependencies]
walkdir = "0.1"
